const fs = require('fs');

// Base64 encoded favicon with Indian flag colors
const faviconBase64 = `
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAA
7AAAAOwBeShxvQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAGUSURBVFiF7ZY9
SwNBEIYfRUQEEQsLCwsLSwv/gKWFhYV/wELs7C0s7O0tLCwsLAQLCxsLCwsLsVBEBBERCZ4xmpjkLnf
7zVIO7oWD293Z2X12Z2dmL6UU+q6pPutPAP8KIEmStCzLm6Io7rvYSzvY3APwAGAHwCqATw0gxpgDAM
cALgDcGGMOAawDmHaxm3bwfA/ANYBLAKcAXgGsAJgJsZ0mSZKmabqbpul+mqZzWZbtZVm2n+f5Rp7n8
yG20xDnxpjL6qOiKB7KsrwrivKpLMvnELtpgO0EwDGA8youdwAOAWyG2E85Fh0BuK0WnQI4ArATYj/z
8P4UwA2AKwAvANYBzIXYzzyynwN4BnBfxeUBwCaAhRD7eUBcZgBmAWQAFgEshNhOPXKfA3gC8ATgFsA
LgA0A8yG2Q5LQZPUYgPcqLi8AtgAsh9hPQ0pxHsBjFZcvVVwWQ+yHlOKQUnwG4L2Ky2sVl6UQ+yGlOK
QUv1Vx+aji8hZiP6QUZwAeAbxWcVkGsBJiP6QULwF4r6R4GcBqiP2QUhz9/zB+AsCv+gZCqtWRvwJ3L
QAAAABJRU5ErkJggg==
`;

// Convert base64 to buffer
const buffer = Buffer.from(faviconBase64, 'base64');

// Write to file
fs.writeFileSync('public/favicon.ico', buffer); 